#!/bin/bash


if [ ! -d env ]; then
    echo "Installing shire dependencies..."
    virtualenv env
    . env/bin/activate
    pip install -r requirements.txt
fi

if [ ! -f data.db ]; then
    export FLASK_APP=shire.py
    flask initdb
fi

echo -e "Setup complete.\nTo run server:\n"
echo -e "source env/bin/activate\ngunicorn --bind 0.0.0.0:8000 shire:app\n"
