#!/bin/bash

export FLASK_APP=shire.py

if [ ! -d env ]; then
    echo "Installing shire dependencies..."
    sleep 1
    virtualenv env
    . env/bin/activate
    pip install -r requirements.txt
fi

if [ ! -f data.db ]; then
    flask initdb
fi

sleep 1
echo "Setup complete."
sleep 2
echo
echo "To run local development server:"
echo
echo "export FLASK_APP=shire.py"
echo ". env/bin/activate"
echo "flask run --host=0.0.0.0"
echo
